export function NeutralAnswer(){
    return(
        <div className="p-2">
            Se você está se sentindo nem triste e nem feliz, pode ser que esteja em um estado de neutralidade emocional. Embora isso possa parecer confortável para algumas pessoas, outras podem achar difícil lidar com essa sensação de falta de emoção. Aqui estão alguns conselhos que podem ajudá-lo:
            <br/><br/><div className="flex gap-1 text-green-blue font-medium">1. <p className="text-black">Identifique o que está causando essa sensação de neutralidade emocional:</p></div> Pergunte a si mesmo se há algo em sua vida que possa estar contribuindo para essa sensação. Pode ser que haja algo que esteja afetando sua emoção, sem que você perceba.
            <br/><br/><div className="flex gap-1 text-green-blue font-medium">2. <p className="text-black">Pratique a autorreflexão:</p></div> Tire um tempo para refletir sobre o que você deseja da vida e sobre o que o faz feliz. Tente se concentrar em suas metas e objetivos, para que você possa encontrar um propósito e significado em sua vida.
            <br/><br/><div className="flex gap-1 text-green-blue font-medium">3. <p className="text-black">Faça algo que você goste:</p></div> Pode ser que você esteja se sentindo assim porque está sobrecarregado com a rotina. Tente fazer algo que o faça sentir bem e feliz, mesmo que seja algo pequeno. Isso pode ajudá-lo a se sentir mais positivo e alegre.
            <br/><br/><div className="flex gap-1 text-green-blue font-medium">4. <p className="text-black">Converse com alguém:</p></div> Às vezes, falar sobre seus sentimentos pode ajudá-lo a entender melhor o que está acontecendo e pode ajudá-lo a encontrar uma solução. Converse com amigos, familiares ou um terapeuta, se necessário.
            <br/><br/><div className="flex gap-1 text-green-blue font-medium">5. <p className="text-black">Cuide de si mesmo:</p></div> Certifique-se de que está dormindo o suficiente, comendo bem e exercitando-se regularmente. O autocuidado pode ajudá-lo a se sentir melhor emocional e fisicamente.
            <br/><br/><div className="flex gap-1 text-green-blue font-medium">6. <p className="text-black">Tente coisas novas:</p></div> Às vezes, a sensação de neutralidade pode ser o resultado da falta de novidades em sua vida. Tente algo novo, um hobby, uma atividade física, ou algo que você sempre quis fazer mas ainda não tentou.
            <br/><br/>Lembre-se de que é normal passar por altos e baixos emocionais. Mas se você sentir que está preso nessa sensação de neutralidade emocional, tente seguir essas dicas para ajudá-lo a se sentir melhor.
        </div>
    )
}